- id: check-uv-lock-vulnerabilities
  name: Check uv.lock for vulnerabilities
  entry: hooks/check-uv-lock-vulnerabilities.sh
  language: script
  stages: [pre-commit]
- id: check-uv-lock-vulnerabilities-daily
  name: Check uv.lock for vulnerabilities (only runs if last successful run was more than 24 hours ago)
  entry: hooks/check-uv-lock-vulnerabilities-daily.sh
  language: script
  stages: [pre-commit]
