- id: check-uv-lock-vulnerabilities
  name: Check uv.lock for vulnerabilities
  entry: check-uv-lock-vulnerabilities
  language: python
  files: ^uv\.lock$
  stages: [pre-commit]
- id: check-uv-lock-vulnerabilities-daily
  name: Check uv.lock for vulnerabilities (only runs if last successful run was more than 24 hours ago)
  entry: check-uv-lock-vulnerabilities-daily
  language: python
  files: ^uv\.lock$
  stages: [pre-commit]
